### ISSUE TITLE
Loading from Dictionary implementation

### ISSUE THREAD

**Issue by SpinnerX** [SpinnerX/RedBlackTreesDictionary#1]
Implement to load from a dictionary, and parse the words that are being read through that dictionary.

**Comment by schmij03** [comment]
Loading the data and saving it in an ArrayList as well as a function which could check if a String is part of the ArrayList has been implemented.

additional arraylist which holds the poem is also implemented. Poem is saved as txt in my fork

**Comment by mrparmesan01** [comment]
Can you re-commit the changes you made, again? There was some conflicts that I realized was happening.

Also, before you commit though, do git pull, and sync your fork before doing the commit, just letting you know.

**Comment by schmij03** [comment]
i pushed it on thursday when there were no changes made as of then.

I now resolved the conflicts

**Comment by mrparmesan01** [comment]
Oh okay, no worries. Would you be able to push the commits again? 

Sry about that lol

**Comment by mrparmesan01** [comment]
Just noting that this Feature has now already been implemented
